//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.19 at 02:17:03 PM EDT 
//

@XmlJavaTypeAdapters({ @XmlJavaTypeAdapter(type = LocalDateTime.class, value = LocalDateTimeXmlAdapter.class) })

@javax.xml.bind.annotation.XmlSchema(namespace = "com.abeosoft.microservices.newsapp.consul.cxf", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.abeosoft.microservices.news.domain;

import java.time.LocalDateTime;

import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapters;

import com.abeosoft.microservices.news.util.LocalDateTimeXmlAdapter;
